<?php 

/*function slx_custom_block_info() {
  // This example comes from node.module.
  $blocks['pie'] = array(
    'info'        => 'Pie de página',
    'status'      => 1,
    'region'      => 'Pie de página',
    'weight'      => 0,
    'visibility'  => 0,
  );
*/

function slx_custom_block_view($delta = '')
{
  switch ($delta)
    {
      /*case 'pie':
        $block['subject'] = '';
        $block['content'] = slx_custom_pie();
      break;*/
      
    }
    return $block;
  }   

/*function slx_custom_pie() {
  $output = '<div class="container_16">
      <div id="logo-marca-agua"><span id="logo-marca-agua-imagen">&nbsp;</span></div>  
      <div class="grid_8">
        <span>Av. de España, 18 - 1º D Cáceres. Teléfono de cita: 927 249 822</span>
      </div>
      
      <div class="grid_8">
        <ul>
          <li><a href="/informacion-legal" title="Información legal">Información legal</a>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
          <li><span>Desarrollado por: </span><a class="solucionex text-indent" target="_blank" href="http://www.solucionex.com" title="Ir a la web de Solucionex">Solucionex</a></li>
        </ul>
      </div>
    </div>';
  
  return $output;
}
*/


/**
 * Implements hook_view().

function slx_custom_view($node, $view_mode) {
  global $user;
  $output = '';

  
  return $node;
}

/**
 * Implementation of hook_menu()

function slx_custom_menu() {
  
  $items['1'] = array (
      'title' => '1',
      'page callback' => 'slx_custom_menu_principal',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      'menu_name' => 'menu-menu-principal-slx-custom',
    );
  
  $vocabulary_array = taxonomy_vocabulary_get_names();
  $vocabulary = $vocabulary_array['seccion'];
  $vid = $vocabulary->vid;
  $taxonomy_tree = taxonomy_get_tree($vid, $parent = 0, $max_depth = NULL, $load_entities = FALSE);
  
  foreach ($taxonomy_tree as $item) {
    $items[$item->name] = array (
      'title' => $item->name,
      'page callback' => 'slx_custom_menu_principal',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      'menu_name' => 'menu-menu-principal-slx-custom',
    );
  }
  
  return $items;
} 


  
function slx_custom_menu_principal($first_name = '', $last_name = ''){
  $vocabulary_array = taxonomy_vocabulary_get_names();
  $vocabulary = $vocabulary_array['seccion'];
  $vid = $vocabulary->vid;
  
  dsm($vocabulary);
  //$vid = $vocabulary[3]->vid; 
  $taxonomy_tree = taxonomy_get_tree($vid, $parent = 0, $max_depth = NULL, $load_entities = FALSE);
  //$vocabulary_children = taxonomy_get_children($tid, $vid)
  dsm($taxonomy_tree);

  $taxonomy_tree_array = array();

  foreach ($taxonomy_tree as $item) {
    $key = $item->tid;
    $value = $item->name;
    if ($item->depth == 0) {
      $taxonomy_tree_array[$key] = $value;
    } else {
      $parents = $item->parents[0];
      print $parents;
      //$taxonomy_tree_array[$parents] = array($key => $value);
    }
  }

  
  //dsm($taxonomy_tree_array);
  return theme('item_list',array('items' => $taxonomy_tree_array));
  //return theme_menu_tree($variables['tree'] = $taxonomy_tree_array);
  
}
  
function _slx_custom_get_taxonomy_items($vid) {
  $result = db_query('SELECT tid, mlid FROM {taxonomy_menu} WHERE vid = :vid', array(':vid' => $vid));
  $menu_items = array();
  $menu_items = $result->fetchAllKeyed();
  return $menu_items;
}

 */